plugins:
  - jekyll-remote-theme

remote_theme: andreondra/jekyll-theme-simplex

title: AD ASTRA
tagline: Thoughts on code, ideas, and everything in between
copyright: © Gutentag0004 2026
favicon: /assets/favicon.ico

sass:
  style: compressed
  silence_deprecations: [import]

collections:
  category:
    output: true
  authors:
    output: false

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
